/**
 * IES Hub v3 — COG export / document generation (C3 client-safe split, 2026-07-22)
 *
 * Pure generation only: analysis state in → CSV text / GeoJSON text /
 * PptxGenJS presentation / print-HTML string out. Mechanically lifted from
 * ui.js (WSC basis-doc.js pattern) so the generators are importable —
 * including by the node test suite — with NO DOM mounts and no global side
 * effects at import time. ui.js stays the thin trigger: guard toasts,
 * downloadCSV/blob clicks, popup open + document.write, and the PptxGenJS
 * CDN lazy-loader all live there.
 *
 * @module tools/center-of-gravity/export
 */

import * as calc from './calc.js?v=20260704-ux2c';
import { printFontCss, FONT_UI, FONT_DISPLAY } from '../../shared/print-fonts.js?v=20260710-r3';
import { icon } from '../../shared/icons.js?v=20260710-r2';
import { escapeHtml } from '../../shared/escape.js?v=20260702-sec2';

/**
 * Build the analysis CSV (pure — caller downloads).
 * Three sections: Summary (6 KPIs), Optimal Centers, Demand Points & Assignments.
 * F1 (P0) — CSV Export
 */
export function buildAnalysisCsv({ cogResult, points, config }) {
  // 2026-05-28 30 — use engine source of truth.
  const costEst = {
    totalCost: cogResult.totalCost ?? 0,
    avgCostPerUnit: cogResult.avgCostPerUnit ?? 0,
    totalTruckloads: cogResult.totalTruckloads ?? 0,
    totalTruckMiles: cogResult.totalTruckMiles ?? 0,
  };
  const now = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  const filename = `cog-analysis-${now}.csv`;

  // Build CSV sections
  const sections = [];

  // Section 1: Summary KPIs
  sections.push('SUMMARY');
  sections.push('Metric,Value');
  sections.push(`Number of Centers,${cogResult.centers.length}`);
  sections.push(`Total Demand Weight,"${points.reduce((s, p) => s + p.weight, 0).toLocaleString()}"`);
  sections.push(`Estimated Annual Transport Cost,"${calc.formatCurrency(costEst.totalCost).replace(/[$,]/g, '')}"`);
  sections.push(`Average Cost per Unit,"${calc.formatCurrency(costEst.avgCostPerUnit).replace(/[$,]/g, '')}"`);
  sections.push(`K-means Iterations,${cogResult.iterations}`);
  sections.push(`Transport Cost per Mile,$${config.transportCostPerMile}`);
  sections.push('');

  // Section 2: Optimal Centers
  sections.push('OPTIMAL CENTERS');
  sections.push('Center,Latitude,Longitude,Nearest City,Assigned Weight,Avg Weighted Distance (mi),Max Distance (mi)');
  cogResult.centers.forEach((c, i) => {
    sections.push(`Center ${i + 1},"${c.lat.toFixed(4)}","${c.lng.toFixed(4)}","${c.nearestCity}","${c.totalWeight.toLocaleString()}","${c.avgWeightedDistance.toFixed(2)}","${c.maxDistance.toFixed(2)}"`);
  });
  sections.push('');

  // Section 3: Demand Points & Assignments
  sections.push('DEMAND POINTS & ASSIGNMENTS');
  sections.push('Name,Latitude,Longitude,Weight,Assigned To Center,Distance to Center (mi),Transport Cost');
  cogResult.assignments.forEach(a => {
    const pt = points.find(p => p.id === a.pointId);
    // 2026-05-28 30 — read from engine source of truth.
    const cbaRow = Array.isArray(cogResult.costByAssignment)
      ? cogResult.costByAssignment.find(x => x.pointId === a.pointId)
      : null;
    const cost = cbaRow ? cbaRow.totalCost : 0;
    if (pt) {
      sections.push(`"${pt.name || pt.id}","${pt.lat.toFixed(4)}","${pt.lng.toFixed(4)}","${pt.weight}","Center ${a.clusterId + 1}","${a.distanceToCenter.toFixed(2)}","${cost.toFixed(2)}"`);
    }
  });

  const csvContent = sections.join('\n');
  return { filename, csv: csvContent };
}

/**
 * 2026-05-28 36 — Per-shipment cost CSV. Every assignment with full
 * cost breakdown — auditable trail for contract negotiation. Rows
 * include: pointId, name, lat, lng, cluster, distance (one-way),
 * road distance (one-way × roadFactor), zone, pkg count, parcel cost,
 * truck cost, total cost.
 */
export function buildPerShipmentCsv({ cogResult, points, config, scenarioName }) {
  const road = Math.max(1, +(config.roadFactor ?? 1.22));
  const now = new Date().toISOString().split('T')[0];
  const filename = `cog-per-shipment-${now}.csv`;
  const lines = [];
  lines.push('# Per-shipment audit CSV — generated by IES Hub COG');
  lines.push(`# Scenario: ${(scenarioName || '(unsaved)').replace(/,/g, ' ')}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# Mode mix on: ${config.modeMixEnabled ? 'yes' : 'no'}`);
  lines.push(`# Carrier: ${config.parcelCarrier || 'fedex_ground'}`);
  lines.push('');
  lines.push('point_id,name,lat,lng,cluster,one_way_mi,road_mi,zone,weight,pkg_count,parcel_cost_usd,truck_cost_usd,total_cost_usd,out_of_sla');
  for (const a of cogResult.assignments) {
    const pt = points.find(p => p.id === a.pointId);
    const cba = Array.isArray(cogResult.costByAssignment) ? cogResult.costByAssignment.find(x => x.pointId === a.pointId) : null;
    const oneWay = a.distanceToCenter || 0;
    const roadMi = oneWay * road;
    const zone = cba?.zone ?? '';
    const pkgs = cba?.pkgCount ?? 0;
    const truckCost = cba?.truckCost ?? 0;
    const parcelCost = cba?.parcelCost ?? 0;
    const totalCost = cba?.totalCost ?? 0;
    const outOfSla = a.outOfService ? '1' : '0';
    const name = (pt?.name || a.pointId).replace(/"/g, "'");
    lines.push([
      `"${a.pointId}"`,
      `"${name}"`,
      pt?.lat != null ? pt.lat.toFixed(4) : '',
      pt?.lng != null ? pt.lng.toFixed(4) : '',
      a.clusterId + 1,
      oneWay.toFixed(2),
      roadMi.toFixed(2),
      zone,
      pt?.weight ?? '',
      pkgs.toFixed(2),
      parcelCost.toFixed(2),
      truckCost.toFixed(2),
      totalCost.toFixed(2),
      outOfSla,
    ].join(','));
  }
  const csv = lines.join('\n');
  return { filename, csv };
}

/**
 * Build the GeoJSON FeatureCollection export (pure — caller downloads).
 * Includes optimal centers as Point features, demand points as Point features
 * with cluster + cost metadata, and center↔demand lines as LineString features.
 * F1 — opens directly in QGIS, kepler.gl, Mapbox, ArcGIS, etc.
 */
export function buildGeoJson({ cogResult, points, config }) {
  const capacity = Math.max(1, config.unitsPerTruck || 25000);
  const features = [];

  // Centers (red star points)
  cogResult.centers.forEach((c, i) => {
    features.push({
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [c.lng, c.lat] },
      properties: {
        kind: 'center',
        cluster_id: i,
        label: `Center ${i + 1}`,
        nearest_city: c.nearestCity,
        assigned_weight: c.totalWeight,
        avg_weighted_distance_mi: Number(c.avgWeightedDistance.toFixed(2)),
        max_distance_mi: Number(c.maxDistance.toFixed(2)),
      },
    });
  });

  // Demand points + center↔point lines
  // 2026-05-28 — pull rt + road factors so per-row annual_transport_cost
  // matches the on-screen Analysis-tab totals. (Same fix as CSV export.)
  const rt = Math.max(1, +config.roundTripFactor || 2.0);
  const road = Math.max(1, +config.roadFactor || 1.22);
  cogResult.assignments.forEach(a => {
    const pt = points.find(p => p.id === a.pointId);
    if (!pt) return;
    const truckloads = (pt.weight || 0) / capacity;
    // 2026-05-28 30 — engine source of truth.
    const cbaRow = Array.isArray(cogResult.costByAssignment)
      ? cogResult.costByAssignment.find(x => x.pointId === a.pointId)
      : null;
    const cost = cbaRow ? cbaRow.totalCost : (a.distanceToCenter * road * truckloads * config.transportCostPerMile * rt);
    features.push({
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [pt.lng, pt.lat] },
      properties: {
        kind: 'demand_point',
        name: pt.name || pt.id,
        cluster_id: a.clusterId,
        weight: pt.weight,
        distance_to_center_mi: Number(a.distanceToCenter.toFixed(2)),
        annual_transport_cost: Number(cost.toFixed(2)),
      },
    });
    const center = cogResult.centers[a.clusterId];
    if (center) {
      features.push({
        type: 'Feature',
        geometry: {
          type: 'LineString',
          coordinates: [[pt.lng, pt.lat], [center.lng, center.lat]],
        },
        properties: {
          kind: 'assignment_line',
          cluster_id: a.clusterId,
          point_name: pt.name || pt.id,
          distance_mi: Number(a.distanceToCenter.toFixed(2)),
        },
      });
    }
  });

  const fc = {
    type: 'FeatureCollection',
    properties: {
      generated: new Date().toISOString(),
      n_centers: cogResult.centers.length,
      n_demand_points: points.length,
      transport_cost_per_mile: config.transportCostPerMile,
      units_per_truck: capacity,
    },
    features,
  };

  const now = new Date().toISOString().split('T')[0];
  const filename = `cog-analysis-${now}.geojson`;
  return { filename, text: JSON.stringify(fc, null, 2) };
}

/**
 * F3 — PowerPoint deck build (pure w.r.t. the page: the PptxGenJS
 * constructor is injected by the caller, which also awaits writeFile).
 * Produces a 6-slide deck:
 *   1. Title — customer + deal context
 *   2. Executive Summary — KPIs + vs-current delta + recommendation
 *   3. Map — US bbox with native shapes (cannot fail; no image deps)
 *   4. Cost Breakdown — per-cluster table + truck/parcel split
 *   5. Sensitivity — k-curve line chart + cost-driver tornado bar chart
 *   6. Assumptions & Recommendation — two-column
 *
 * Palette: dark navy (0A1628), amber (F59E0B), ice blue (CADCFC).
 */
export function buildPptxDeck({ PptxGenJSCtor, cogResult, points, solvePoints, sensitivityData, config, scenarioName }) {
    const pres = new PptxGenJSCtor();
    pres.layout = 'LAYOUT_WIDE'; // 13.3" x 7.5"
    pres.author = 'GXO IES Solutions Design';
    pres.company = 'GXO Logistics';
    const today = new Date();
    const dateStr = today.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
    const customerName = (config.customerName || '').trim();
    const industryLabel = (calc.INDUSTRY_OPTIONS.find(o => o.value && o.value === config.industry) || {}).label || '';
    const stageLabel = (calc.DEAL_STAGES.find(o => o.value && o.value === config.dealStage) || {}).label || '';
    const scenName = scenarioName || 'Untitled scenario';
    pres.title = `COG ${customerName ? customerName + ' — ' : ''}${dateStr}`;

    // Palette
    const C = {
      navy: '0A1628', navySoft: '0D1F3C', amber: 'F59E0B',
      ice: 'CADCFC', white: 'FFFFFF', gray100: 'F8FAFC',
      gray200: 'E2E8F0', gray400: '94A3B8', gray500: '64748B',
      gray700: '334155', good: '16A34A', bad: 'DC2626',
    };
    const fmtMoney = (v) => '$' + Math.round(v || 0).toLocaleString();
    const fmtMoneyCompact = (v) => {
      const n = Math.abs(v || 0);
      if (n >= 1e9) return '$' + (v / 1e9).toFixed(1) + 'B';
      if (n >= 1e6) return '$' + (v / 1e6).toFixed(1) + 'M';
      if (n >= 1e3) return '$' + (v / 1e3).toFixed(0) + 'K';
      return '$' + Math.round(v || 0);
    };
    const fmtPct = (v, dp = 1) => (v == null ? '—' : v.toFixed(dp) + '%');
    const fmtNum = (v) => (v == null ? '—' : Math.round(v).toLocaleString());

    // Pull data
    const numCenters = cogResult.centers.length;
    const totalCost = cogResult.totalCost || 0;
    const truckCost = cogResult.truckCost || 0;
    const parcelCost = cogResult.parcelCost || 0;
    const parcelOn = parcelCost > 0;
    const co2Tons = cogResult.co2Tons || 0;
    const coverage = cogResult.serviceStats?.maxMiles > 0 ? cogResult.serviceStats.coveragePct : null;
    // Phase 2c (2026-06-10): solve-set weight, matching the engine + KPI strip
    const totalDemand = solvePoints.reduce((s, p) => s + (p.weight || 0), 0);
    const costPerUnit = totalDemand > 0 ? totalCost / totalDemand : 0;
    const co2Display = co2Tons >= 1000 ? (co2Tons / 1000).toFixed(1) + ' kt' : co2Tons.toFixed(0) + ' t';

    // vs-current-state benchmark (re-computed inline; matches Network Benchmark)
    let vsCurrent = null;
    try {
      const csList = (config.currentStateDCs || []).filter(d => Number.isFinite(+d.lat) && Number.isFinite(+d.lng));
      if (csList.length > 0) {
        const solvePts = solvePoints;
        const csMcr = calc.buildMcrFromDcList(csList, solvePts);
        if (csMcr) {
          const csCost = calc.estimateBlendedCost(csMcr, solvePts, config);
          calc.flagServiceViolations(csMcr, solvePts, config.maxServiceMiles ?? 0, config.roadFactor ?? 1.22);
          const csCo2 = ((csCost.totalTruckMiles || 0) * (config.co2KgPerTruckMile ?? 1.62) + (csCost.parcelDetails?.totalPackages || 0) * (+config.parcelCo2KgPerPkg || 0.5)) / 1000; // 2026-06-10: truck + parcel, symmetric with proposed-side co2Tons
          vsCurrent = {
            n: csList.length,
            cost: csCost.totalCost,
            co2Tons: csCo2,
            coverage: csMcr.serviceStats?.maxMiles > 0 ? csMcr.serviceStats.coveragePct : null,
            costDelta: totalCost - csCost.totalCost,
            costDeltaPct: csCost.totalCost > 0 ? ((totalCost - csCost.totalCost) / csCost.totalCost * 100) : 0,
            co2Delta: co2Tons - csCo2,
          };
        }
      }
    } catch (e) { console.warn('[F3] vs-current calc failed:', e); }

    // ============================================================
    // Slide 1: Title
    // ============================================================
    let s = pres.addSlide();
    s.background = { color: C.navy };
    // Top accent strip
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.18, fill: { color: C.amber }, line: { color: C.amber } });
    // GXO IES wordmark top-left
    s.addText('GXO IES · Solutions Design', { x: 0.6, y: 0.5, w: 6, h: 0.4, fontSize: 12, fontFace: 'Calibri', color: C.amber, bold: true, charSpacing: 4 });
    // Date top-right
    s.addText(dateStr, { x: 7, y: 0.5, w: 5.7, h: 0.4, fontSize: 12, fontFace: 'Calibri', color: C.ice, align: 'right' });

    // Customer name (huge centered)
    const customerHeadline = customerName || scenName;
    s.addText(customerHeadline, { x: 0.6, y: 2.0, w: 12.1, h: 1.5, fontSize: 54, fontFace: 'Calibri', color: C.white, bold: true, align: 'center', valign: 'middle' });
    // Subtitle
    s.addText('Center of Gravity Analysis', { x: 0.6, y: 3.5, w: 12.1, h: 0.55, fontSize: 26, fontFace: 'Calibri', color: C.ice, align: 'center' });
    // Context line
    const ctxBits = [industryLabel, stageLabel, customerName ? null : `Scenario: ${scenName}`].filter(Boolean);
    if (ctxBits.length) {
      s.addText(ctxBits.join('   ·   '), { x: 0.6, y: 4.15, w: 12.1, h: 0.4, fontSize: 14, fontFace: 'Calibri', color: C.ice, align: 'center' });
    }
    // Headline KPIs at bottom of title
    s.addText([
      { text: String(numCenters), options: { fontSize: 44, color: C.amber, bold: true, breakLine: true } },
      { text: numCenters === 1 ? 'distribution center' : 'distribution centers', options: { fontSize: 12, color: C.ice } },
    ], { x: 1.5, y: 5.4, w: 3, h: 1.3, fontFace: 'Calibri', align: 'center', valign: 'top', margin: 0 });
    s.addText([
      { text: fmtMoneyCompact(totalCost), options: { fontSize: 44, color: C.amber, bold: true, breakLine: true } },
      { text: 'annual network cost', options: { fontSize: 12, color: C.ice } },
    ], { x: 5.15, y: 5.4, w: 3, h: 1.3, fontFace: 'Calibri', align: 'center', valign: 'top', margin: 0 });
    s.addText([
      { text: coverage != null ? fmtPct(coverage, 0) : co2Display, options: { fontSize: 44, color: C.amber, bold: true, breakLine: true } },
      { text: coverage != null ? 'within service SLA' : 'annual CO\u2082', options: { fontSize: 12, color: C.ice } },
    ], { x: 8.8, y: 5.4, w: 3, h: 1.3, fontFace: 'Calibri', align: 'center', valign: 'top', margin: 0 });
    // Bottom accent strip
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 7.32, w: 13.3, h: 0.18, fill: { color: C.amber }, line: { color: C.amber } });

    // ============================================================
    // Slide 2: Executive Summary
    // ============================================================
    s = pres.addSlide();
    s.background = { color: C.white };
    // Header bar
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.85, fill: { color: C.navy }, line: { color: C.navy } });
    s.addText('Executive Summary', { x: 0.6, y: 0.18, w: 8, h: 0.5, fontSize: 22, fontFace: 'Calibri', color: C.white, bold: true });
    s.addText(customerHeadline + (industryLabel ? '  ·  ' + industryLabel : ''), { x: 0.6, y: 0.5, w: 12.1, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.ice });

    // 4 KPI cards across the top
    const kpiCards = [
      { label: 'Distribution Centers', value: String(numCenters), sub: numCenters === 1 ? 'single-DC network' : `${numCenters} DCs in solution` },
      { label: 'Annual Network Cost', value: fmtMoneyCompact(totalCost), sub: `${fmtMoney(costPerUnit)} per unit` },
      { label: 'Service Coverage', value: coverage != null ? fmtPct(coverage, 0) : 'n/a', sub: coverage != null ? `within ${cogResult.serviceStats?.maxMiles || 0}-mi SLA` : 'no SLA defined' },
      { label: 'Annual CO\u2082', value: co2Display, sub: `truck ${(config.co2KgPerTruckMile ?? 1.62).toFixed(2)} kg/mi + parcel ${(+config.parcelCo2KgPerPkg || 0.5).toFixed(2)} kg/pkg` },
    ];
    kpiCards.forEach((k, i) => {
      const x = 0.6 + i * 3.1;
      // Card background
      s.addShape(pres.shapes.RECTANGLE, { x, y: 1.2, w: 2.9, h: 1.7, fill: { color: C.gray100 }, line: { color: C.gray200, width: 1 } });
      // Accent bar (left side)
      s.addShape(pres.shapes.RECTANGLE, { x, y: 1.2, w: 0.08, h: 1.7, fill: { color: C.amber }, line: { color: C.amber } });
      // Label
      s.addText(k.label, { x: x + 0.22, y: 1.32, w: 2.6, h: 0.3, fontSize: 10, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 2, margin: 0 });
      // Value (big)
      s.addText(k.value, { x: x + 0.22, y: 1.62, w: 2.6, h: 0.85, fontSize: 36, fontFace: 'Calibri', color: C.navy, bold: true, margin: 0 });
      // Sub
      s.addText(k.sub, { x: x + 0.22, y: 2.5, w: 2.6, h: 0.32, fontSize: 10, fontFace: 'Calibri', color: C.gray500, margin: 0 });
    });

    // vs-Current panel (if available)
    if (vsCurrent) {
      const goodCost = vsCurrent.costDelta < 0;
      s.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 3.1, w: 12.1, h: 1.7, fill: { color: C.white }, line: { color: C.navy, width: 1.5 } });
      s.addText('vs. Current State Network', { x: 0.8, y: 3.2, w: 6, h: 0.36, fontSize: 12, fontFace: 'Calibri', color: C.navy, bold: true, charSpacing: 3 });
      s.addText(`Benchmarked against ${vsCurrent.n} current DC${vsCurrent.n === 1 ? '' : 's'}`, { x: 0.8, y: 3.5, w: 6, h: 0.3, fontSize: 10, fontFace: 'Calibri', color: C.gray500 });
      // Three delta KPIs
      const deltas = [
        { label: 'Cost Δ', value: (vsCurrent.costDelta >= 0 ? '+' : '') + fmtMoneyCompact(vsCurrent.costDelta), sub: (vsCurrent.costDelta >= 0 ? '+' : '') + vsCurrent.costDeltaPct.toFixed(1) + '%', color: Math.abs(vsCurrent.costDelta) < 100 ? C.navy : (goodCost ? C.good : C.bad) },
        { label: 'CO\u2082 Δ', value: (vsCurrent.co2Delta >= 0 ? '+' : '') + Math.round(vsCurrent.co2Delta).toLocaleString() + ' t', sub: vsCurrent.co2Tons > 0 ? ((vsCurrent.co2Delta / vsCurrent.co2Tons * 100).toFixed(0) + '%') : '—', color: Math.abs(vsCurrent.co2Delta) < 1 ? C.navy : (vsCurrent.co2Delta < 0 ? C.good : C.bad) },
        { label: 'Network', value: numCenters + ' vs ' + vsCurrent.n, sub: numCenters < vsCurrent.n ? 'consolidation' : (numCenters > vsCurrent.n ? 'expansion' : 'same footprint'), color: C.navy },
      ];
      deltas.forEach((d, i) => {
        const dx = 7.0 + i * 1.85;
        s.addText(d.label, { x: dx, y: 3.2, w: 1.7, h: 0.3, fontSize: 9, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 2, margin: 0 });
        s.addText(d.value, { x: dx, y: 3.5, w: 1.7, h: 0.7, fontSize: 26, fontFace: 'Calibri', color: d.color, bold: true, margin: 0 });
        s.addText(d.sub, { x: dx, y: 4.2, w: 1.7, h: 0.3, fontSize: 10, fontFace: 'Calibri', color: C.gray500, margin: 0 });
      });
    }

    // Recommendation block
    const recoY = vsCurrent ? 5.0 : 3.3;
    s.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: recoY, w: 12.1, h: 2.0, fill: { color: C.navy }, line: { color: C.navy } });
    s.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: recoY, w: 0.12, h: 2.0, fill: { color: C.amber }, line: { color: C.amber } });
    s.addText('RECOMMENDATION', { x: 0.95, y: recoY + 0.15, w: 6, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.amber, bold: true, charSpacing: 4 });
    const primaryCity = cogResult.centers[0]?.nearestCity?.split('(')[0].trim() || 'the centroid location';
    const recoLines = [];
    if (numCenters === 1) {
      recoLines.push(`Operate a single distribution center in ${primaryCity} to serve ${fmtNum(points.length)} demand points totaling ${fmtNum(totalDemand)} weight units.`);
    } else {
      const cities = cogResult.centers.map(c => c.nearestCity?.split('(')[0].trim()).filter(Boolean).slice(0, 4).join(', ');
      recoLines.push(`Operate ${numCenters} distribution centers across ${cities || 'the recommended footprint'} to serve ${fmtNum(points.length)} demand points.`);
    }
    if (vsCurrent && vsCurrent.costDelta < 0) {
      recoLines.push(`Saves ${fmtMoneyCompact(Math.abs(vsCurrent.costDelta))} per year (${Math.abs(vsCurrent.costDeltaPct).toFixed(1)}%) vs the current ${vsCurrent.n}-DC network.`);
    } else if (vsCurrent && vsCurrent.costDelta > 0) {
      recoLines.push(`Adds ${fmtMoneyCompact(Math.abs(vsCurrent.costDelta))} per year (${vsCurrent.costDeltaPct.toFixed(1)}%) vs current — value is in service/CO\u2082 not pure cost.`);
    }
    recoLines.push(`Annual landed cost ${fmtMoney(costPerUnit)} per unit at ${fmtNum(totalDemand)} units of demand.`);
    s.addText(recoLines.join('\n'), { x: 0.95, y: recoY + 0.5, w: 11.6, h: 1.4, fontSize: 14, fontFace: 'Calibri', color: C.white, valign: 'top', paraSpaceAfter: 6 });

    // Slide 2 footer
    s.addText(`Scenario: ${scenName}  ·  Generated ${dateStr}`, { x: 0.6, y: 7.1, w: 12.1, h: 0.25, fontSize: 9, fontFace: 'Calibri', color: C.gray400 });

    // ============================================================
    // Slide 3: Map
    // ============================================================
    s = pres.addSlide();
    s.background = { color: C.white };
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.85, fill: { color: C.navy }, line: { color: C.navy } });
    s.addText('Network Map', { x: 0.6, y: 0.18, w: 8, h: 0.5, fontSize: 22, fontFace: 'Calibri', color: C.white, bold: true });
    s.addText(`${numCenters} center${numCenters === 1 ? '' : 's'}  ·  ${fmtNum(points.length)} demand points`, { x: 0.6, y: 0.5, w: 12.1, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.ice });

    // Map bbox: continental US — lng -125 to -65, lat 24 to 50
    const mapX = 0.6, mapY = 1.15, mapW = 12.1, mapH = 5.85;
    const lngL = -125, lngR = -65, latT = 50, latB = 24;
    const project = (lat, lng) => ({
      x: mapX + ((lng - lngL) / (lngR - lngL)) * mapW,
      y: mapY + ((latT - lat) / (latT - latB)) * mapH,
    });
    // Map background
    s.addShape(pres.shapes.RECTANGLE, { x: mapX, y: mapY, w: mapW, h: mapH, fill: { color: C.gray100 }, line: { color: C.gray200, width: 1 } });
    // Crude US continent shape — a single rounded rect to suggest land mass
    // (don't try to draw the actual outline — keeps the slide editable)
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: mapX + 0.6, y: mapY + 0.5, w: mapW - 1.2, h: mapH - 1.0, fill: { color: 'EDF2F7' }, line: { color: 'CBD5E1', width: 1 }, rectRadius: 0.15 });
    // Labels for region (rough)
    s.addText('UNITED STATES', { x: mapX + 4, y: mapY + 2.5, w: 4.5, h: 0.4, fontSize: 14, fontFace: 'Calibri', color: 'B0BEC5', bold: true, align: 'center', charSpacing: 8 });

    // Demand points — sampled for visual cleanliness (max 400 dots)
    const validPts = points.filter(p => Number.isFinite(+p.lat) && Number.isFinite(+p.lng) && +p.lat >= latB && +p.lat <= latT && +p.lng >= lngL && +p.lng <= lngR);
    const maxDots = 400;
    const step = Math.max(1, Math.ceil(validPts.length / maxDots));
    const sampledPts = validPts.filter((_, i) => i % step === 0);
    sampledPts.forEach(pt => {
      const { x: px, y: py } = project(+pt.lat, +pt.lng);
      s.addShape(pres.shapes.OVAL, { x: px - 0.04, y: py - 0.04, w: 0.08, h: 0.08, fill: { color: 'F87171', transparency: 50 }, line: { color: 'F87171', width: 0 } });
    });

    // Service zones for each center
    const validCenters = cogResult.centers.filter(c => Number.isFinite(+c.lat) && Number.isFinite(+c.lng));
    const clusterColors = ['0047AB', '22C55E', 'F59E0B', '8B5CF6', 'EC4899', '06B6D4', 'EF4444', '14B8A6'];
    validCenters.forEach((c, i) => {
      const { x: cx, y: cy } = project(+c.lat, +c.lng);
      const color = clusterColors[i % clusterColors.length];
      // Service zone ring — 500 mi at this projection (~7.25 lat degrees, varies but use lat for approx)
      const ringDeg = 500 / 69; // ~7.25 deg
      const ringPx = (ringDeg / (latT - latB)) * mapH;
      s.addShape(pres.shapes.OVAL, { x: cx - ringPx, y: cy - ringPx, w: ringPx * 2, h: ringPx * 2, fill: { color: color, transparency: 92 }, line: { color: color, width: 1, dashType: 'dash' } });
    });
    // Centers (drawn on top of zones)
    validCenters.forEach((c, i) => {
      const { x: cx, y: cy } = project(+c.lat, +c.lng);
      const color = clusterColors[i % clusterColors.length];
      // Halo
      s.addShape(pres.shapes.OVAL, { x: cx - 0.22, y: cy - 0.22, w: 0.44, h: 0.44, fill: { color: C.white }, line: { color: C.white } });
      // Center dot
      s.addShape(pres.shapes.OVAL, { x: cx - 0.18, y: cy - 0.18, w: 0.36, h: 0.36, fill: { color: color }, line: { color: C.navy, width: 2 } });
      // Label
      s.addText('C' + (i + 1), { x: cx - 0.18, y: cy - 0.18, w: 0.36, h: 0.36, fontSize: 11, fontFace: 'Calibri', color: C.white, bold: true, align: 'center', valign: 'middle', margin: 0 });
      // City label below
      const city = c.nearestCity?.split('(')[0].trim();
      if (city) {
        s.addText(city, { x: cx - 1.0, y: cy + 0.22, w: 2.0, h: 0.3, fontSize: 10, fontFace: 'Calibri', color: C.navy, bold: true, align: 'center', margin: 0 });
      }
    });

    // Legend
    s.addShape(pres.shapes.RECTANGLE, { x: mapX + 0.15, y: mapY + mapH - 0.65, w: 4.2, h: 0.5, fill: { color: C.white, transparency: 10 }, line: { color: C.gray200, width: 1 } });
    s.addShape(pres.shapes.OVAL, { x: mapX + 0.3, y: mapY + mapH - 0.5, w: 0.18, h: 0.18, fill: { color: clusterColors[0] }, line: { color: C.navy, width: 1.5 } });
    s.addText('Distribution center', { x: mapX + 0.55, y: mapY + mapH - 0.55, w: 1.6, h: 0.3, fontSize: 9, fontFace: 'Calibri', color: C.gray700, margin: 0 });
    s.addShape(pres.shapes.OVAL, { x: mapX + 2.2, y: mapY + mapH - 0.5, w: 0.1, h: 0.1, fill: { color: 'F87171' }, line: { color: 'F87171' } });
    s.addText('Demand point (sampled)', { x: mapX + 2.4, y: mapY + mapH - 0.55, w: 1.9, h: 0.3, fontSize: 9, fontFace: 'Calibri', color: C.gray700, margin: 0 });

    s.addText('Approximate positions. Ring = 500-mi service zone.', { x: mapX, y: mapY + mapH + 0.05, w: mapW, h: 0.25, fontSize: 8, fontFace: 'Calibri', color: C.gray400, italic: true });

    // ============================================================
    // Slide 4: Cost Breakdown
    // ============================================================
    s = pres.addSlide();
    s.background = { color: C.white };
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.85, fill: { color: C.navy }, line: { color: C.navy } });
    s.addText('Cost Breakdown', { x: 0.6, y: 0.18, w: 8, h: 0.5, fontSize: 22, fontFace: 'Calibri', color: C.white, bold: true });
    s.addText(`Annual: ${fmtMoneyCompact(totalCost)}  ·  $${costPerUnit.toFixed(2)}/unit`, { x: 0.6, y: 0.5, w: 12.1, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.ice });

    // Per-cluster table
    const tableHead = [
      { text: '#', options: { bold: true, color: C.white, fill: { color: C.navy }, align: 'center' } },
      { text: 'Center', options: { bold: true, color: C.white, fill: { color: C.navy } } },
      { text: 'Demand', options: { bold: true, color: C.white, fill: { color: C.navy }, align: 'right' } },
      { text: '% of total', options: { bold: true, color: C.white, fill: { color: C.navy }, align: 'right' } },
      { text: 'Avg distance', options: { bold: true, color: C.white, fill: { color: C.navy }, align: 'right' } },
      { text: 'Annual cost', options: { bold: true, color: C.white, fill: { color: C.navy }, align: 'right' } },
    ];
    const totalWtForTable = cogResult.centers.reduce((sm, c) => sm + (c.totalWeight || 0), 0) || 1;
    const tableBody = cogResult.centers.map((c, i) => {
      const cost = Array.isArray(cogResult.costByCluster) ? (cogResult.costByCluster[i] || 0) : 0;
      const pct = (c.totalWeight || 0) / totalWtForTable * 100;
      return [
        { text: 'C' + (i + 1), options: { bold: true, color: clusterColors[i % clusterColors.length], align: 'center' } },
        { text: c.nearestCity || 'Center ' + (i + 1), options: { color: C.navy } },
        { text: fmtNum(c.totalWeight), options: { align: 'right', color: C.navy } },
        { text: pct.toFixed(1) + '%', options: { align: 'right', color: C.gray500 } },
        { text: Math.round(c.avgWeightedDistance || 0) + ' mi', options: { align: 'right', color: C.gray500 } },
        { text: fmtMoneyCompact(cost), options: { align: 'right', color: C.navy, bold: true } },
      ];
    });
    s.addTable([tableHead, ...tableBody], {
      x: 0.6, y: 1.15, w: 12.1, h: Math.min(3.5, 0.4 + cogResult.centers.length * 0.35),
      colW: [0.7, 4.0, 2.0, 1.6, 2.0, 1.8],
      fontSize: 11, fontFace: 'Calibri', border: { type: 'solid', pt: 0.5, color: C.gray200 },
    });

    // Truck vs Parcel split (if parcel engine)
    const splitY = Math.min(5.0, 1.5 + cogResult.centers.length * 0.35 + 0.4);
    if (parcelOn && totalCost > 0) {
      s.addText('Mode mix', { x: 0.6, y: splitY, w: 6, h: 0.3, fontSize: 12, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 3 });
      const barY = splitY + 0.4;
      const barW = 12.1;
      const truckShare = Math.max(0, Math.min(1, truckCost / totalCost));
      const parcelShare = Math.max(0, Math.min(1, parcelCost / totalCost));
      s.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: barY, w: barW * truckShare, h: 0.55, fill: { color: '3B82F6' }, line: { color: '3B82F6' } });
      s.addShape(pres.shapes.RECTANGLE, { x: 0.6 + barW * truckShare, y: barY, w: barW * parcelShare, h: 0.55, fill: { color: C.amber }, line: { color: C.amber } });
      // Labels on bar
      if (truckShare > 0.08) s.addText(`TRUCK  ${(truckShare * 100).toFixed(0)}%  ${fmtMoneyCompact(truckCost)}`, { x: 0.6, y: barY, w: barW * truckShare, h: 0.55, fontSize: 11, fontFace: 'Calibri', color: C.white, bold: true, align: 'center', valign: 'middle', margin: 0 });
      if (parcelShare > 0.08) s.addText(`PARCEL  ${(parcelShare * 100).toFixed(0)}%  ${fmtMoneyCompact(parcelCost)}`, { x: 0.6 + barW * truckShare, y: barY, w: barW * parcelShare, h: 0.55, fontSize: 11, fontFace: 'Calibri', color: C.white, bold: true, align: 'center', valign: 'middle', margin: 0 });
    }

    // ============================================================
    // Slide 5: Sensitivity
    // ============================================================
    s = pres.addSlide();
    s.background = { color: C.white };
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.85, fill: { color: C.navy }, line: { color: C.navy } });
    s.addText('Sensitivity Analysis', { x: 0.6, y: 0.18, w: 8, h: 0.5, fontSize: 22, fontFace: 'Calibri', color: C.white, bold: true });
    s.addText('How does cost respond to network size and to changes in key drivers?', { x: 0.6, y: 0.5, w: 12.1, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.ice });

    // Left: k vs cost line chart
    if (Array.isArray(sensitivityData) && sensitivityData.length > 0) {
      s.addText('Network size vs annual cost', { x: 0.6, y: 1.1, w: 6, h: 0.3, fontSize: 12, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 3 });
      const kLabels = sensitivityData.map(d => String(d.k));
      const kValues = sensitivityData.map(d => Math.round(d.totalCost || 0));
      s.addChart(pres.charts.LINE, [{ name: 'Annual cost', labels: kLabels, values: kValues }], {
        x: 0.6, y: 1.5, w: 6.0, h: 5.0,
        chartColors: [C.amber],
        chartArea: { fill: { color: C.white } },
        catAxisLabelColor: C.gray500, catAxisLabelFontSize: 10,
        valAxisLabelColor: C.gray500, valAxisLabelFontSize: 10,
        valGridLine: { color: C.gray200, size: 0.5 },
        catGridLine: { style: 'none' },
        lineSize: 3, lineSmooth: true,
        showValue: false, showLegend: false,
        valAxisLabelFormatCode: '$#,##0,K',
        catAxisTitle: 'Number of DCs (k)', catAxisTitleColor: C.gray700, catAxisTitleFontSize: 10, showCatAxisTitle: true,
        valAxisTitle: 'Annual cost', valAxisTitleColor: C.gray700, valAxisTitleFontSize: 10, showValAxisTitle: true,
      });
      // Recommended-k callout
      const recRow = sensitivityData.find(d => d.isRecommended || d.recommended);
      if (recRow) {
        s.addText(`Recommended k = ${recRow.k}  ·  ${fmtMoneyCompact(recRow.totalCost)}/yr`, { x: 0.6, y: 6.55, w: 6.0, h: 0.3, fontSize: 10, fontFace: 'Calibri', color: C.navy, bold: true, align: 'center' });
      }
    } else {
      s.addText('Sensitivity data not available — run analysis with multiple k values.', { x: 0.6, y: 2.5, w: 6.0, h: 0.5, fontSize: 12, fontFace: 'Calibri', color: C.gray500, italic: true });
    }

    // Right: Cost-driver tornado as horizontal bar chart
    try {
      const tornado = calc.tornadoSensitivity(cogResult, solvePoints, config); // Phase 2c: solve set
      if (Array.isArray(tornado) && tornado.length > 0) {
        s.addText('Cost-driver tornado', { x: 6.9, y: 1.1, w: 6, h: 0.3, fontSize: 12, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 3 });
        // Take top 6 drivers by absolute swing
        const top = tornado.slice(0, 6);
        const labels = top.map(d => d.label);
        const swings = top.map(d => Math.round(d.swing || 0));
        s.addChart(pres.charts.BAR, [{ name: 'Cost swing ($)', labels, values: swings }], {
          x: 6.9, y: 1.5, w: 6.0, h: 5.0,
          barDir: 'bar',
          chartColors: [C.navy],
          chartArea: { fill: { color: C.white } },
          catAxisLabelColor: C.gray700, catAxisLabelFontSize: 10,
          valAxisLabelColor: C.gray500, valAxisLabelFontSize: 9,
          valGridLine: { color: C.gray200, size: 0.5 },
          catGridLine: { style: 'none' },
          showValue: true, dataLabelColor: C.navy, dataLabelFontSize: 9,
          dataLabelPosition: 'outEnd', dataLabelFormatCode: '$#,##0,K',
          showLegend: false,
          valAxisLabelFormatCode: '$#,##0,K',
        });
        s.addText('Each bar shows the cost swing when that driver varies \u00b1 its range.', { x: 6.9, y: 6.55, w: 6.0, h: 0.3, fontSize: 9, fontFace: 'Calibri', color: C.gray400, italic: true, align: 'center' });
      }
    } catch (e) {
      console.warn('[F3] tornado calc failed:', e);
    }

    // ============================================================
    // Slide 6: Assumptions & Recommendation
    // ============================================================
    s = pres.addSlide();
    s.background = { color: C.white };
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 13.3, h: 0.85, fill: { color: C.navy }, line: { color: C.navy } });
    s.addText('Assumptions & Next Steps', { x: 0.6, y: 0.18, w: 8, h: 0.5, fontSize: 22, fontFace: 'Calibri', color: C.white, bold: true });
    s.addText('Key parameters driving this analysis. Adjust to model alternatives.', { x: 0.6, y: 0.5, w: 12.1, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.ice });

    // Left column — Assumptions table
    const assumpRows = [
      ['Demand points', fmtNum(points.length)],
      ['Total demand', fmtNum(totalDemand) + ' ' + (config.weightUnit || 'lb')],
      ['Cost / mile', '$' + (config.transportCostPerMile || 2.85).toFixed(2)],
      ['Road factor', (config.roadFactor ?? 1.22).toFixed(2) + ' × great-circle'],
      ['Round-trip factor', (config.roundTripFactor ?? 2.0).toFixed(2) + 'x'],
      ['Units / truck', fmtNum(config.unitsPerTruck || 25000)],
      ['Fixed cost / DC', '$' + Math.round(config.fixedCostPerDC || 0).toLocaleString() + '/yr'],
    ];
    if (parcelOn) {
      assumpRows.push(['Parcel share', (config.modeMix?.parcelPct ?? 0) + '%']);
      assumpRows.push(['Avg pkg weight', (config.parcelAvgPackageWeightLb ?? 5) + ' lb']);
      assumpRows.push(['Parcel carrier', config.parcelCarrier || 'fedex']);
      if (config.parcelContractDiscountPct) assumpRows.push(['Contract discount', config.parcelContractDiscountPct + '%']);
    }
    if (config.maxServiceMiles > 0) assumpRows.push(['Service SLA', config.maxServiceMiles + ' mi']);
    assumpRows.push(['CO\u2082 / truck-mile', (config.co2KgPerTruckMile ?? 1.62).toFixed(2) + ' kg']);

    s.addText('ASSUMPTIONS', { x: 0.6, y: 1.1, w: 6, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 4 });
    const assumpTable = assumpRows.map(([k, v]) => [
      { text: k, options: { color: C.gray700, fontSize: 11, valign: 'middle' } },
      { text: v, options: { color: C.navy, fontSize: 11, bold: true, align: 'right', valign: 'middle' } },
    ]);
    s.addTable(assumpTable, {
      x: 0.6, y: 1.45, w: 6.0, colW: [3.6, 2.4],
      fontFace: 'Calibri', border: { type: 'solid', pt: 0.5, color: C.gray200 }, rowH: 0.32,
    });

    // Right column — Next Steps
    s.addText('NEXT STEPS', { x: 7.0, y: 1.1, w: 6, h: 0.3, fontSize: 11, fontFace: 'Calibri', color: C.gray500, bold: true, charSpacing: 4 });
    const nextSteps = [
      { text: 'Validate the demand data — confirm point counts, weight units, and any excluded geographies.', options: { bullet: true, breakLine: true, color: C.navy } },
      { text: 'Walk the recommended footprint with operations — labor, real estate availability, lease cost.', options: { bullet: true, breakLine: true, color: C.navy } },
      { text: 'Tune cost-per-mile and round-trip factor against the customer\u2019s actual carrier rates.', options: { bullet: true, breakLine: true, color: C.navy } },
      { text: 'Run sensitivity on growth — model 1, 3, and 5-yr horizons if growth > 5% / yr.', options: { bullet: true, breakLine: true, color: C.navy } },
      { text: 'Compare against a current-state benchmark — load the current DC list under Parameters.', options: { bullet: true, color: C.navy } },
    ];
    s.addText(nextSteps, { x: 7.0, y: 1.45, w: 6.0, h: 4.5, fontSize: 12, fontFace: 'Calibri', paraSpaceAfter: 8 });

    // Footer
    s.addShape(pres.shapes.RECTANGLE, { x: 0, y: 7.05, w: 13.3, h: 0.45, fill: { color: C.gray100 }, line: { color: C.gray100 } });
    s.addText('GXO IES Solutions Design  ·  Center of Gravity Engine v3', { x: 0.6, y: 7.13, w: 6, h: 0.3, fontSize: 9, fontFace: 'Calibri', color: C.gray500 });
    s.addText(`${customerHeadline}  ·  ${dateStr}`, { x: 6.7, y: 7.13, w: 6.0, h: 0.3, fontSize: 9, fontFace: 'Calibri', color: C.gray500, align: 'right' });

    // Save
    const safeCustomer = (customerName || 'scenario').replace(/[^a-z0-9-]+/gi, '-').slice(0, 40);
    const fname = `cog-${safeCustomer}-${today.toISOString().split('T')[0]}.pptx`;
  return { pres, fname };
}

/**
 * 2026-05-28 F4 — Build the print-friendly snapshot HTML (pure string).
 * The caller opens the popup and document.write()s this; the user then
 * uses the browser's native Print > Save as PDF.
 *
 * The print HTML is self-contained — inline styles, no JS — so it
 * survives the popup's blank-document boot and doesn't depend on any
 * loaded modules. (That's also why it keeps raw hex colors: the popup
 * document never loads css/hub.css, so --ies-* / --c-* tokens don't resolve.)
 */
export function buildPrintHtml({ cogResult, points, solvePoints, config, scenarioName: scenarioNameRaw, cpm }) {
  const solvePts = solvePoints;
  // 2026-05-28 30 — engine source of truth.
  const costEst = {
    totalCost: cogResult.totalCost ?? 0,
    avgCostPerUnit: cogResult.avgCostPerUnit ?? 0,
    totalTruckloads: cogResult.totalTruckloads ?? 0,
    totalTruckMiles: cogResult.totalTruckMiles ?? 0,
  };
  const today = new Date().toISOString().split('T')[0];
  const ctxParts = [config.customerName, config.industry ? (calc.INDUSTRY_OPTIONS.find(o => o.value === config.industry) || {}).label : null, config.dealStage ? (calc.DEAL_STAGES.find(o => o.value === config.dealStage) || {}).label : null].filter(Boolean);
  const ctxLine = ctxParts.length ? ctxParts.join(' · ') : 'Untitled scenario';
  const scenarioName = scenarioNameRaw || '(unsaved)';
  const fmtMoney = (v) => '$' + (v || 0).toLocaleString('en-US', { maximumFractionDigits: 0 });
  const fmtMi = (v) => Math.round(v).toLocaleString() + ' mi';
  const co2 = cogResult.co2Tons || 0;
  const co2Str = co2 >= 1000 ? (co2 / 1000).toFixed(1) + ' kt' : co2 >= 1 ? co2.toFixed(0) + ' t' : (co2 * 1000).toFixed(0) + ' kg';
  const coverage = cogResult.serviceStats?.maxMiles > 0 ? cogResult.serviceStats.coveragePct.toFixed(1) + '%' : 'n/a';

  const html = `<!doctype html>
<html><head><meta charset="utf-8"/>
<title>COG Analysis — ${scenarioName.replace(/</g, '&lt;')} — ${today}</title>
<style>
  ${printFontCss()}
  @page { size: letter portrait; margin: 0.5in; }
  body { font-family: ${FONT_UI}; color: #0a1628; background: #fff; margin: 0; padding: 0; font-size: 12px; line-height: 1.4; }
  .doc { max-width: 7.5in; margin: 0 auto; padding: 16px 0; }
  h1 { font-family: ${FONT_DISPLAY}; font-size: 21px; letter-spacing: -0.015em; margin: 0 0 4px; color: #0a1628; }
  h2 { font-family: ${FONT_DISPLAY}; font-size: 15px; letter-spacing: -0.01em; margin: 18px 0 8px; color: #0a1628; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; }
  .meta { color: #475569; font-size: 11px; margin-bottom: 16px; }
  .kpi-strip { display: grid; grid-template-columns: repeat(5, 1fr); gap: 8px; margin-bottom: 16px; background: linear-gradient(135deg, #0a1628, #0d1f3c); color: #fff; padding: 12px 16px; border-radius: 6px; }
  .kpi { font-size: 11px; }
  .kpi-label { font-size: 9px; text-transform: uppercase; letter-spacing: 0.3px; opacity: 0.7; }
  .kpi-value { font-size: 18px; font-weight: 800; line-height: 1.1; margin-top: 2px; font-variant-numeric: tabular-nums; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; font-variant-numeric: tabular-nums; }
  thead { background: #f1f5f9; }
  th { text-align: left; padding: 6px 8px; font-weight: 700; border: 1px solid #cbd5e1; }
  td { padding: 5px 8px; border: 1px solid #e2e8f0; }
  .right { text-align: right; }
  .center-card { padding: 10px 12px; margin-bottom: 8px; border: 1px solid #e2e8f0; border-radius: 4px; page-break-inside: avoid; }
  .center-card-head { font-weight: 700; font-size: 12px; margin-bottom: 6px; }
  .center-card-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; font-size: 10px; }
  .center-card-grid .lbl { color: #475569; font-size: 9px; text-transform: uppercase; }
  .center-card-grid .val { font-weight: 700; }
  .breakdown { background: #f8fafc; border-left: 3px solid #475569; padding: 10px 14px; margin-bottom: 12px; font-family: 'SFMono-Regular', Consolas, Menlo, monospace; font-size: 10px; line-height: 1.6; }
  .footer { margin-top: 16px; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 8px; }
  .toolbar { padding: 8px 16px; background: #f1f5f9; border-bottom: 1px solid #cbd5e1; display: flex; gap: 8px; align-items: center; font-size: 11px; }
  .toolbar button { padding: 5px 12px; font-size: 11px; border: 1px solid #475569; background: #fff; border-radius: 4px; cursor: pointer; }
  @media print { .toolbar { display: none; } body { background: #fff; } }
</style>
</head><body>
<div class="toolbar">
  <strong>Print preview — use your browser's Print menu to Save as PDF.</strong>
  <button onclick="window.print()" style="margin-left:auto;">${icon('printer')} Print now</button>
  <button onclick="window.close()">Close</button>
</div>
<div class="doc">
  <h1>${scenarioName.replace(/</g, '&lt;')}</h1>
  <div class="meta">${ctxLine.replace(/</g, '&lt;')} · Center of Gravity analysis · ${today}</div>

  <div class="kpi-strip" style="grid-template-columns:repeat(6, 1fr);">
    <div class="kpi"><div class="kpi-label">Centers</div><div class="kpi-value">${cogResult.centers.length}</div></div>
    <div class="kpi"><div class="kpi-label">Truckloads/yr</div><div class="kpi-value">${Math.round(costEst.totalTruckloads || 0).toLocaleString()}</div></div>
    <div class="kpi"><div class="kpi-label">Annual cost</div><div class="kpi-value">${fmtMoney(costEst.totalCost)}</div></div>
    <div class="kpi"><div class="kpi-label">Cost / unit</div><div class="kpi-value">$${(costEst.avgCostPerUnit || 0).toFixed(4)}</div></div>
    <div class="kpi"><div class="kpi-label">CO₂/yr</div><div class="kpi-value">${co2Str}</div></div>
    <div class="kpi"><div class="kpi-label">Coverage</div><div class="kpi-value">${coverage}</div></div>
  </div>
  ${cogResult.parcelDetails ? `
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:16px;background:#f1f5f9;border-left:3px solid #14b8a6;padding:10px 14px;border-radius:4px;font-size:11px;">
      <div><div style="font-size:9px;text-transform:uppercase;color:#475569;letter-spacing:0.3px;">Truck (TL+LTL)</div><div style="font-size:15px;font-weight:800;color:#0a1628;font-variant-numeric:tabular-nums;">${fmtMoney(cogResult.truckCost || 0)}<span style="font-size:10px;font-weight:500;color:#64748b;"> &nbsp;${costEst.totalCost > 0 ? ((cogResult.truckCost || 0) / costEst.totalCost * 100).toFixed(0) : 0}%</span></div></div>
      <div><div style="font-size:9px;text-transform:uppercase;color:#475569;letter-spacing:0.3px;">Parcel</div><div style="font-size:15px;font-weight:800;color:#0a1628;font-variant-numeric:tabular-nums;">${fmtMoney(cogResult.parcelCost || 0)}<span style="font-size:10px;font-weight:500;color:#64748b;"> &nbsp;${costEst.totalCost > 0 ? ((cogResult.parcelCost || 0) / costEst.totalCost * 100).toFixed(0) : 0}%</span></div></div>
      <div><div style="font-size:9px;text-transform:uppercase;color:#475569;letter-spacing:0.3px;">Packages/yr</div><div style="font-size:15px;font-weight:800;color:#0a1628;font-variant-numeric:tabular-nums;">${Math.round(cogResult.parcelDetails.totalPackages || 0).toLocaleString()}<span style="font-size:10px;font-weight:500;color:#64748b;"> &nbsp;${(cogResult.parcelDetails.carrier || '').replace(/_/g, ' ')}</span></div></div>
    </div>
  ` : ''}

  <h2>Cost calculation</h2>
  ${cogResult.parcelDetails ? `
    <div class="breakdown">
      <strong>Truck slice (TL+LTL):</strong><br/>
      ${Math.round(costEst.totalTruckloads || 0).toLocaleString()} truckloads × weighted avg distance × ${(config.roadFactor ?? 1.22).toFixed(2)} road × ${(config.roundTripFactor ?? 2.0).toFixed(1)} round-trip<br/>
      = ${Math.round(costEst.totalTruckMiles || 0).toLocaleString()} truck-mi/yr × $${(cpm || 0).toFixed(2)}/mi (blended)<br/>
      = <strong>${fmtMoney(cogResult.truckCost || 0)}/yr</strong><br/>
      <br/>
      <strong>Parcel slice (${(cogResult.parcelDetails.carrier || '').replace(/_/g, ' ')}):</strong><br/>
      ${Math.round(cogResult.parcelDetails.totalPackages || 0).toLocaleString()} pkgs/yr × zone-priced rate (avg ${(cogResult.parcelDetails.avgWeight || 0).toFixed(1)} lb)<br/>
      + ${(cogResult.parcelDetails.fuelPct || 0).toFixed(0)}% fuel · ${(cogResult.parcelDetails.residentialShare * 100 || 0).toFixed(0)}% residential${(cogResult.parcelDetails.discountPct || 0) > 0 ? ` · −${(cogResult.parcelDetails.discountPct || 0).toFixed(0)}% contract discount` : ''}<br/>
      = <strong>${fmtMoney(cogResult.parcelCost || 0)}/yr</strong> (avg $${cogResult.parcelDetails.totalPackages > 0 ? ((cogResult.parcelCost || 0) / cogResult.parcelDetails.totalPackages).toFixed(2) : '0.00'}/pkg)<br/>
      <br/>
      <strong>Total: ${fmtMoney(costEst.totalCost)}/yr</strong> · CO₂ (truck ${(config.co2KgPerTruckMile ?? 1.62).toFixed(2)} kg/mi + parcel ${(+config.parcelCo2KgPerPkg || 0.5).toFixed(2)} kg/pkg) = <strong>${co2Str}/yr</strong>
    </div>
    <h2>Parcel zone distribution</h2>
    <table>
      <thead><tr><th>Zone</th><th class="right">Range (miles)</th><th class="right">Packages</th><th class="right">% of total</th></tr></thead>
      <tbody>
        ${[
          { z: 2, lo: 0,    hi: 150 },
          { z: 3, lo: 151,  hi: 300 },
          { z: 4, lo: 301,  hi: 600 },
          { z: 5, lo: 601,  hi: 1000 },
          { z: 6, lo: 1001, hi: 1400 },
          { z: 7, lo: 1401, hi: 1800 },
          { z: 8, lo: 1801, hi: 999999 },
        ].map(b => {
          const n = (cogResult.parcelDetails.byZone || {})[b.z] || 0;
          const tot = cogResult.parcelDetails.totalPackages || 0;
          const pct = tot > 0 ? (n / tot * 100) : 0;
          if (n <= 0) return '';
          const range = b.hi >= 999999 ? `${b.lo.toLocaleString()}+` : `${b.lo.toLocaleString()}–${b.hi.toLocaleString()}`;
          return `<tr><td>Z${b.z}</td><td class="right">${range}</td><td class="right">${Math.round(n).toLocaleString()}</td><td class="right">${pct.toFixed(1)}%</td></tr>`;
        }).join('')}
      </tbody>
    </table>
  ` : `
    <div class="breakdown">
      ${solvePts.length} active demand points × ${(config.unitsPerTruck || 25000).toLocaleString()} ${(calc.getWeightUnitMeta(config.weightUnit || 'lb').short || 'units')}/truck<br/>
      ${Math.round(costEst.totalTruckloads || 0).toLocaleString()} truckloads × weighted avg distance × ${(config.roadFactor ?? 1.22).toFixed(2)} road × ${(config.roundTripFactor ?? 2.0).toFixed(1)} round-trip<br/>
      = ${Math.round(costEst.totalTruckMiles || 0).toLocaleString()} truck-mi/yr × $${(cpm || 0).toFixed(2)}/mi<br/>
      = <strong>${fmtMoney(costEst.totalCost)}/yr</strong> · CO₂ at ${(config.co2KgPerTruckMile ?? 1.62).toFixed(2)} kg/mi = <strong>${co2Str}/yr</strong>
    </div>
  `}

  ${(() => {
    const horizon = Math.max(1, +config.analysisHorizonYears || 1);
    if (horizon <= 1) return '';
    const proj = calc.multiYearCostProjection(costEst.totalCost || 0, config);
    const growth = +config.annualGrowthPct || 0;
    const escalation = +config.annualEscalationPct || 0;
    const discount = +config.discountRatePct || 0;
    return `
      <h2>${horizon}-year cost projection</h2>
      <div class="breakdown" style="background:linear-gradient(135deg,#fffbeb,#f0fdf4);border-left-color:#15803d;">
        <strong>${horizon}-yr cumulative:</strong> ${fmtMoney(proj.totalCost)} ·
        <strong>${horizon}-yr NPV @ ${discount}%:</strong> ${fmtMoney(proj.totalNpv)} ·
        <strong>Year-${horizon} annual:</strong> ${fmtMoney(proj.years[proj.years.length - 1].cost)}<br/>
        Assumptions: ${growth >= 0 ? '+' : ''}${growth}% volume growth/yr · +${escalation}% rate escalation/yr · ${discount}% discount (WACC)
      </div>
      <table>
        <thead><tr><th>Year</th><th class="right">Annual cost</th><th class="right">Cumulative</th><th class="right">Discounted (PV)</th></tr></thead>
        <tbody>
          ${proj.years.map(y => `<tr><td>Year ${y.year}</td><td class="right">${fmtMoney(y.cost)}</td><td class="right">${fmtMoney(y.cumulative)}</td><td class="right">${fmtMoney(y.npv)}</td></tr>`).join('')}
          <tr style="border-top:2px solid #475569;font-weight:700;background:#f1f5f9;"><td>${horizon}-yr total</td><td class="right"></td><td class="right">${fmtMoney(proj.totalCost)}</td><td class="right">${fmtMoney(proj.totalNpv)}</td></tr>
        </tbody>
      </table>
    `;
  })()}

  <h2>Recommended centers</h2>
  ${cogResult.centers.map((c, i) => {
    const tCost = Array.isArray(cogResult.truckCostByCluster) ? cogResult.truckCostByCluster[i] : 0;
    const pCost = Array.isArray(cogResult.parcelCostByCluster) ? cogResult.parcelCostByCluster[i] : 0;
    const tot = Array.isArray(cogResult.costByCluster) ? cogResult.costByCluster[i] : 0;
    return `
    <div class="center-card">
      <div class="center-card-head">Center ${i + 1}: ${(c.nearestCity || '').replace(/</g, '&lt;')}${c.candidateLabel ? ` (snapped → ${c.candidateLabel.replace(/</g, '&lt;')})` : ''}</div>
      <div class="center-card-grid">
        <div><div class="lbl">Location</div><div class="val">${c.lat.toFixed(4)}, ${c.lng.toFixed(4)}</div></div>
        <div><div class="lbl">Assigned weight</div><div class="val">${(c.totalWeight || 0).toLocaleString()}</div></div>
        <div><div class="lbl">Avg distance</div><div class="val">${fmtMi(c.avgWeightedDistance)}</div></div>
        <div><div class="lbl">Annual cost</div><div class="val">${fmtMoney(tot)}</div></div>
      </div>
      ${cogResult.parcelDetails ? `
        <div class="center-card-grid" style="margin-top:6px;border-top:1px dashed #cbd5e1;padding-top:6px;">
          <div><div class="lbl">Truck cost</div><div class="val">${fmtMoney(tCost)}</div></div>
          <div><div class="lbl">Parcel cost</div><div class="val">${fmtMoney(pCost)}</div></div>
          <div><div class="lbl">Parcel share</div><div class="val">${tot > 0 ? (pCost / tot * 100).toFixed(0) : 0}%</div></div>
          <div><div class="lbl">$ / unit</div><div class="val">$${c.totalWeight > 0 ? (tot / c.totalWeight).toFixed(3) : '0.000'}</div></div>
        </div>
      ` : ''}
    </div>
  `;
  }).join('')}

  <h2>Demand point assignments</h2>
  <table>
    <thead><tr>
      <th>Point</th><th class="right">Lat</th><th class="right">Lng</th><th class="right">Weight</th><th class="right">Cluster</th><th class="right">Distance</th>
    </tr></thead>
    <tbody>
      ${cogResult.assignments.map(a => {
        const pt = points.find(p => p.id === a.pointId);
        if (!pt) return '';
        return `<tr>
          <td>${escapeHtml(pt.name || pt.id)}${a.outOfService ? ' <strong style="color:#b91c1c;">[OUT]</strong>' : ''}</td>
          <td class="right">${pt.lat.toFixed(3)}</td>
          <td class="right">${pt.lng.toFixed(3)}</td>
          <td class="right">${(pt.weight || 0).toLocaleString()}</td>
          <td class="right">${a.clusterId + 1}</td>
          <td class="right">${fmtMi(a.distanceToCenter)}</td>
        </tr>`;
      }).join('')}
    </tbody>
  </table>

  <div class="footer">Generated by IES Hub · Center of Gravity · ${today}</div>
</div>
</body></html>`;

  return html;
}
