-- ============================================================
-- WSC N2 — Design-factor catalog seed (2026-07-04)
-- North Star re-founding, phase N2. Seeds the citable engineering factors
-- (research 2026-07-04, adversarially verified — 5 corrections applied)
-- into ref_planning_ratios under four new wsc_* categories.
--
-- Governance (Brock 2026-07-04): CM House-Assumptions pinning pattern —
-- scenarios pin these at first use (config_data.pinnedFactors), drift
-- badge on catalog change, explicit adopt.
-- Flue default (Brock 2026-07-04): FM Global DS 8-9.
--
-- Provenance convention in `source`:
--   standard | industry method | vendor heuristic | IES assumption
-- Idempotent by REPLACE: the natural-key unique index treats NULLs as
-- distinct, so ON CONFLICT can't dedupe these rows — instead the seed
-- deletes its own namespace (ratio_code LIKE 'wsc.%') and re-inserts.
-- ============================================================

DELETE FROM ref_planning_ratios WHERE ratio_code LIKE 'wsc.%';

INSERT INTO ref_heuristic_categories (code, display_name, description, sort_order) VALUES
  ('wsc_media_selection',   'WSC — Storage media selection',   'Depth-of-inventory thresholds, occupancy floors, density gains, cost bands driving engineered media selection', 190),
  ('wsc_dynamics',          'WSC — Dock / staging / aisles',   'Throughput-derived dock math, dwell-driven staging, MHE-derived aisle widths', 200),
  ('wsc_layout_compliance', 'WSC — Layout & compliance',       'Flue spaces (FM vs NFPA), egress, sprinkler clearance, column-grid coordination', 210),
  ('wsc_profile_defaults',  'WSC — Profile & height economics','Sparse-mode defaults, growth buffers, clear-height economics', 220)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref_planning_ratios
  (category_code, ratio_code, display_name, description, value_type, numeric_value, value_unit, value_jsonb, source, source_detail, source_date, sort_order, notes)
VALUES
-- ── Media selection ──
('wsc_media_selection','wsc.media.rule_of_3','Rule of 3 (deep-lane feasibility)','Average pallets-per-SKU must be ≥ 3× lane depth to sustain the occupancy floor in any deep-lane system.','scalar',3,'x lane depth',NULL,'vendor heuristic','3D Storage Systems — Inventory Analysis: Pallets per SKU and Choosing Lane Depth','2026-05-01',10,'Single-vendor lineage (~35 yrs claimed use); consistent with Bartholdi/Derhami lane-depth literature. Verification: PLAUSIBLE, not a standard.'),
('wsc_media_selection','wsc.media.occupancy_floor_pct','Deep-lane occupancy floor','Minimum acceptable planned occupancy for any deep-lane storage system.','percent',75,'%',NULL,'vendor heuristic','3D Storage Systems','2026-05-01',20,'Stricter 87.5% variant exists (divide pallets/SKU by 4).'),
('wsc_media_selection','wsc.media.selective_planning_occupancy_pct','Selective rack planning occupancy','Plan selective rack at ≤85% occupancy — the 85% rule.','percent',85,'%',NULL,'industry method','Tompkins et al. via Logistics Bureau / FLEX; widely corroborated','2026-07-04',30,'Verification: CONFIRMED.'),
('wsc_media_selection','wsc.media.depth_to_media_map','Depth-of-inventory → media map','Recommended media by average pallets-per-SKU (4-high basis).','lookup',NULL,NULL,'[{"minPltPerSku":1,"maxPltPerSku":5,"media":["selective"]},{"minPltPerSku":6,"maxPltPerSku":8,"media":["double_deep","pushback_2d"]},{"minPltPerSku":9,"maxPltPerSku":14,"media":["pushback_2_3d"]},{"minPltPerSku":15,"maxPltPerSku":23,"media":["pushback_3_4d"]},{"minPltPerSku":24,"maxPltPerSku":35,"media":["drive_in_2d","pushback_4_5d","flow_8d"]},{"minPltPerSku":36,"maxPltPerSku":47,"media":["drive_in_3d","flow_12d"]},{"minPltPerSku":48,"maxPltPerSku":71,"media":["drive_in_4_5d","flow_20d"]},{"minPltPerSku":72,"maxPltPerSku":null,"media":["drive_in_6d","pushback_6d","flow_24d"]}]'::jsonb,'vendor heuristic','3D Storage Systems depth table; direction corroborated by dealer guidance','2026-05-01',40,'Pallet flow not recommended <24 plt/SKU; flow best <100 total SKUs. Buckets mirror profile-calc DEPTH_BUCKETS.'),
('wsc_media_selection','wsc.media.double_deep_density_gain_pct','Double-deep density gain vs selective','Position-density increase moving selective → double-deep.','lookup',NULL,'%','{"min":20,"max":40}'::jsonb,'industry method','Trimet / Better Storage / ECSE, corroborated','2026-07-04',50,'Verification: CONFIRMED at 20–40%.'),
('wsc_media_selection','wsc.media.pushback_density_gain_max_pct','Push-back density gain ceiling','Maximum credible density gain vs selective for push-back.','percent',75,'%',NULL,'industry method','Cisco-Eagle / Camara; verification pass','2026-07-04',60,'OEM "+100%" claim did NOT survive adversarial verification — capped at +75%.'),
('wsc_media_selection','wsc.media.flow_min_pallets_per_sku','Pallet-flow entry threshold','Minimum avg pallets-per-SKU before pallet flow is recommended.','scalar',24,'plt/SKU',NULL,'vendor heuristic','3D Storage Systems','2026-05-01',70,NULL),
('wsc_media_selection','wsc.media.cost_per_position_usd','Cost per pallet position (equipment, 2025–26 USD)','Purchase cost bands by media, hardware only (excl. install/permits/seismic).','lookup',NULL,'USD/position','{"selective":{"min":80,"max":120},"drive_in":{"min":60,"max":110},"pushback":{"min":150,"max":400},"pallet_flow":{"min":250,"max":500},"shuttle_rack":{"min":300,"max":412},"shuttle_bot_each":{"min":30000,"max":40000}}'::jsonb,'industry method','Hammerhead pricing guide 2026-03 + verification corrections (SRS, 3D Storage)','2026-03-01',80,'Pallet-flow band verification-CORRECTED from $550–850 → $250–500. Seismic adds 20–30%.'),
-- ── Dynamics ──
('wsc_dynamics','wsc.dock.mulcahy_safety_factor','Dock doors — Mulcahy safety factor','Annualized dock-count formula: trucks/yr × hrs/truck ÷ work-hrs/yr × SF.','scalar',1.25,'x',NULL,'industry method','Mulcahy, Warehouse Distribution & Operations Handbook pp. 4.18–.20','2026-07-04',10,'Verification: CONFIRMED with page citation.'),
('wsc_dynamics','wsc.dock.peak_safety_factor','Dock doors — peak-day safety factor','Gross & Associates peak-day formula safety factor range (higher because it starts from peak).','lookup',NULL,'x','{"min":1.5,"max":2.0}'::jsonb,'industry method','Gross & Associates via Chuck Berger dock-planning article','2026-07-04',20,'Use arrival-WINDOW hours, not shift hours (4Front adjustment).'),
('wsc_dynamics','wsc.dock.palletized_pallets_per_door_hr','Palletized unload rate','Planning rate per door-hour, palletized trailer with forklifts.','lookup',NULL,'plt/door-hr','{"min":20,"max":35}'::jsonb,'industry method','Red Stag / AMZ Prep / MBC, corroborated','2026-07-04',30,'Floor-loaded doors turn ~3–5× slower — dominant driver of import-DC door counts.'),
('wsc_dynamics','wsc.dock.floor_load_cartons_per_hr','Floor-load unload rate','Cartons/hr with extendable conveyor; uniform boxes at top of band.','lookup',NULL,'ctn/hr','{"irregular":200,"mixed":500,"uniform":1000}'::jsonb,'industry method','Red Stag Fulfillment','2026-07-04',40,NULL),
('wsc_dynamics','wsc.dock.door_per_sqft_sanity','Doors per sqft (SANITY CHECK ONLY)','Distribution rule of thumb — print beside computed answer, never design from it.','lookup',NULL,'sqft/door','{"min":5000,"max":10000}'::jsonb,'industry method','Steelco / MetricRig, corroborated','2026-07-04',50,'Ratio varies 2–3× across sources; throughput math governs.'),
('wsc_dynamics','wsc.staging.min_sqft_per_door','Staging floor minimum per door','One trailer footprint single-deep (60ft × 8.5ft).','scalar',510,'sqft/door',NULL,'industry method','MBC Management dock-design guide','2026-07-04',60,'Floor, not target — dwell-driven formula governs.'),
('wsc_dynamics','wsc.staging.net_density_factor','Staging net density factor','Net staging pallet footprint ÷ 0.5 (×2) for work/travel aisles.','scalar',0.5,'ratio',NULL,'industry method','WarehouseBlueprint staging model','2026-07-04',70,'Dwell time is the dominant sensitivity: 2-day dwell multiplies staging 4–16×.'),
('wsc_dynamics','wsc.aisle.widths_by_mhe_ft','Aisle widths by MHE','Clear-aisle planning bands; governing formula = right-angle stack + load length + 12in.','lookup',NULL,'ft','{"counterbalance":{"min":12,"max":13},"reach":{"min":8,"max":10},"double_deep_reach":{"min":9,"max":10},"vna_turret_clear_in":66,"vna_rack_to_rack_in":72,"order_picker":{"min":4,"max":5}}'::jsonb,'industry method','Conger / Toyota / WarehouseIQ, corroborated; OEM reach minimums 7.5–8 ft','2026-07-04',80,'Verification: reach band widened 8–9 → 8–10 ft. VNA requires F-min floor spec (ACI 360 / defined-traffic).'),
('wsc_dynamics','wsc.aisle.narrow_aisle_storage_gain_pct','Storage gain from aisle narrowing','12ft→8ft ≈ +15–20%; NA ≈ +25%; VNA up to +50%.','lookup',NULL,'%','{"na_8ft":{"min":15,"max":25},"vna_max":50}'::jsonb,'industry method','Conger','2026-07-04',90,NULL),
-- ── Layout & compliance ──
('wsc_layout_compliance','wsc.flue.default_standard','Flue-space governing standard (default)','Which insurer standard WSC assumes when the project has not answered — per-project toggle overrides.','lookup',NULL,NULL,'{"default":"FM","options":["FM","NFPA"]}'::jsonb,'IES assumption','Brock decision 2026-07-04 (GXO book skews FM-insured)','2026-07-04',10,'The client''s insurer decides which governs; unanswered = data gap in the Design Basis doc.'),
('wsc_layout_compliance','wsc.flue.fm_ds8_9','FM Global DS 8-9 flue spaces','Net 3in transverse minimum; longitudinal NOT required in double-row racks at any height; no random variation allowed.','lookup',NULL,'in','{"transverse_net_in":3,"longitudinal_required":false,"transverse_max_spacing_ft":4.5,"spacing_relaxes_to_ft_at_6in":9}'::jsonb,'standard','FM Global Data Sheet 8-9; Risk Logic comparison','2026-07-04',20,'Verification: CONFIRMED incl. spacing nuance.'),
('wsc_layout_compliance','wsc.flue.nfpa_13','NFPA 13 flue spaces','Nominal 6in transverse ≤25ft storage (longitudinal not required); >25ft adds nominal 6in longitudinal in double-row racks.','lookup',NULL,'in','{"transverse_nominal_in":6,"longitudinal_required_above_ft":25,"longitudinal_nominal_in":6,"random_variation_permitted":true}'::jsonb,'standard','NFPA 13 via UpCodes + Risk Logic','2026-07-04',30,'Annex: ~3in is minimum that passes water. Verify adopted edition per AHJ on live projects.'),
('wsc_layout_compliance','wsc.egress.s1_travel_ft','IBC S-1 exit-access travel distance','250 ft sprinklered; 400 ft where F-1/S-1 portion is single-story, ≥24 ft floor-to-deck, sprinklered (§1017.2.2).','lookup',NULL,'ft','{"sprinklered":250,"single_story_24ft_clear":400}'::jsonb,'standard','IBC 2024 §1017.2 / §1017.2.2 via UpCodes','2026-07-04',40,'Measured along walking path around racks, not straight-line.'),
('wsc_layout_compliance','wsc.sprinkler.deflector_clearance_in','Sprinkler deflector clearance','Minimum clearance below sprinkler deflectors to top of storage.','scalar',18,'in',NULL,'standard','OSHA 1910.159 / NFPA 13','2026-07-04',50,NULL),
('wsc_layout_compliance','wsc.grid.column_spacing_ft','Column grid conventions','Class-A grids 50–56 ft; 60 ft speed bay at dock wall; rack-bay fit math governs the choice.','lookup',NULL,'ft','{"min":50,"max":56,"speed_bay":60,"seven_96in_bays_need_ft":58}'::jsonb,'industry method','Link Logistics / Chuck Berger / Eng-Tips; verification-corrected bay arithmetic','2026-07-04',60,'Verification: seven 96in bays + uprights ≈ 58 ft, NOT 56 — bury columns in rack rows, check flue conflicts.'),
-- ── Profile defaults & height economics ──
('wsc_profile_defaults','wsc.profile.default_peak_factor','Default peak factor (sparse mode)','Peak-week ÷ average-week factor assumed when no order history exists.','scalar',1.35,'x',NULL,'IES assumption','Sparse-mode default — replace with derived peak when data arrives (flagged as gap)','2026-07-04',10,'Mirrors profile-calc DEFAULT_PEAK_FACTOR.'),
('wsc_profile_defaults','wsc.profile.default_abc_split','Default ABC split (sparse mode)','Pareto banding assumed when no pick data exists.','lookup',NULL,'%','{"A":{"skuPct":20,"linePct":80},"B":{"skuPct":30,"linePct":15},"C":{"skuPct":50,"linePct":5}}'::jsonb,'industry method','Pareto convention, corroborated (TH Logistics / Plant Engineering / Red Stag)','2026-07-04',20,'Mirrors profile-calc DEFAULT_ABC.'),
('wsc_profile_defaults','wsc.profile.growth_buffer_pct','Design-year growth buffer','Capacity buffer over current volumes for the design year.','lookup',NULL,'%','{"min":20,"max":30}'::jsonb,'industry method','Link Logistics / Crown LSP','2026-07-04',30,'Horizon disagreement in sources: lease-term vs 12–18 months — make explicit per project.'),
('wsc_profile_defaults','wsc.height.capacity_gain_per_ft_pct','Capacity gain per added clear foot','Additional storage capacity per foot of clear height (diminishing with height).','lookup',NULL,'%/ft','{"min":5,"max":10}'::jsonb,'industry method','Racklify / CBRE-derived; verification-softened from 7–10%','2026-07-04',40,NULL),
('wsc_profile_defaults','wsc.height.esfr_ceiling_only_max_ft','ESFR ceiling-only protection limit','Above this building height, in-rack sprinklers enter and change the rack cost model.','lookup',NULL,'ft','{"min":40,"max":45}'::jsonb,'industry method','OPSdesign / NFPA 13 commentary','2026-07-04',50,NULL),
('wsc_profile_defaults','wsc.height.class_a_clear_ft','Clear-height market tiers','Legacy 28–32; Class-A standard 32–36; e-comm/AS-RS 40+.','lookup',NULL,'ft','{"legacy":{"min":28,"max":32},"class_a":{"min":32,"max":36},"ecomm_asrs_min":40}'::jsonb,'industry method','Link Logistics, corroborated','2026-07-04',60,NULL);
