ALTER TABLE cost_model_vas
  ADD COLUMN IF NOT EXISTS service_type VARCHAR DEFAULT 'custom',
  ADD COLUMN IF NOT EXISTS uph NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS labor_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS material_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS space_sf NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS volume_source VARCHAR DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS volume_pct NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS volume_line_id UUID,
  ADD COLUMN IF NOT EXISTS labor_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_cost NUMERIC DEFAULT 0;