ALTER TABLE cost_model_projects
  ADD COLUMN IF NOT EXISTS shift_2_premium NUMERIC DEFAULT 0.10,
  ADD COLUMN IF NOT EXISTS shift_3_premium NUMERIC DEFAULT 0.15,
  ADD COLUMN IF NOT EXISTS absence_allowance_pct NUMERIC DEFAULT 0.12;