
-- Create missing cost_model_volumes table
CREATE TABLE IF NOT EXISTS public.cost_model_volumes (
  id bigint generated by default as identity primary key,
  project_id bigint references public.cost_model_projects(id) on delete cascade,
  volume_name text,
  annual_volume numeric default 0,
  uom text default 'units',
  source text,
  notes text
);

-- Enable RLS
ALTER TABLE public.cost_model_volumes ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated access (matches other CM tables)
CREATE POLICY "Allow all access to cost_model_volumes" ON public.cost_model_volumes
  FOR ALL USING (true) WITH CHECK (true);

-- Add annual_cost alias column to overhead if it doesn't exist
ALTER TABLE public.cost_model_overhead ADD COLUMN IF NOT EXISTS annual_cost numeric;

-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
